; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = platformio_secrets.ini

[common]
lib_deps =
	jandrassy/ArduinoOTA@^1.1.1
	symlink://../SharedLibraries/FreeRTOSPort
	symlink://../SharedLibraries/Communication
	symlink://../SharedLibraries/Logger
	symlink://../SharedLibraries/ICanBus
	symlink://../SharedLibraries/CanMessage
	symlink://../SharedLibraries/CanQueue
	symlink://../SharedLibraries/CanMessageIds
	symlink://../SharedLibraries/CanId
	symlink://../SharedLibraries/CanMessages
	symlink://../SharedLibraries/LargeCanMessage
	symlink://../SharedLibraries/LargeCanMessageHandler
build_flags = 
	-DLOG_LEVEL=3

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
lib_deps = 
	${common.lib_deps}
build_flags = ${common.build_flags}
	-DCANTX=10
	-DCANRX=13
	-DOTA_AP_SSID=\"${ota_secrets.ssid}\"
	-DOTA_AP_PASS=\"${ota_secrets.pass}\"
	-DOTA_PASSWORD=\"${ota_secrets.password}\"

[env:uno_r4_wifi_ota]
extends = env:uno_r4_wifi
upload_protocol = custom
upload_port = ${ota_secrets.ip}
extra_scripts = pre:../SharedLibraries/ota_upload.py

[env:uno_r4_minima]
platform = renesas-ra
board = uno_r4_minima
framework = arduino
lib_deps = 
	${common.lib_deps}
build_flags = ${common.build_flags}
	-DCANTX=11
	-DCANRX=12
